### PR TITLE
Added missing declarations after the last fix

### PR DESCRIPTION
**Pull request by isolin**
Fixes https://github.com/zhuker/lamejs/issues/86

### CODE REVIEW

**Review by F1sher-Man — APPROVED** [review]
Came across the same issue described by isolin. This seems to fix problems.

**Comment by AnshVM** [comment]
Someone please merge this pull request.

**Comment by ulf1** [comment]
Hello @zhuker we are require this fix too

**Comment by DamianDugan** [comment]
Can we hope to see this included in a release ? We are heavily depending on it.

**Comment by giquieu** [comment]
Very good! I'm also waiting for the release.

**Comment by ayunami2000** [comment]
bump

**Comment by anastasia-anisimova** [comment]
Hello @zhuker!
When we will see a release with this fix?

**Comment by Roywcm** [comment]
I also would like to see this released ^^

**Comment by georgehess** [comment]
When will this be updated in the npm?

**Comment by HoonBaek** [comment]
I just applied this fix to my local files (in node_modules),, I will be really appreciated if you release the latest version
@zhuker 🙏

**Comment by christopher-kapic** [comment]
@zhuker Can you please make a new release?

**Comment by axetroy** [comment]
@zhuker  Can you please make a new release?

**Pull request merged**
